[workspace]
members = [
        "lampo-common",
        "lampod",
        "lampod-cli",
        "lampo-cli",
        "lampo-bitcoind",
        "lampo-jsonrpc",
        "lampo-client",
        "lampo-c-ffi",
        "lampo-core-wallet",
        "lampo-testing",
        "lampo-bdk-wallet",
        "tests/tests",
]

default-members = [
        "lampo-common",
        "lampod",
        "lampod-cli",
        "lampo-cli",
        "lampo-bitcoind",
        "lampo-jsonrpc",
        "lampo-client",
        "lampo-c-ffi",
        "lampo-bdk-wallet",
        "lampo-core-wallet",
]
resolver = "2"
