[package]
name = "lampod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
lampo-common = { path = "../lampo-common" }
lampo-jsonrpc = { path = "../lampo-jsonrpc" }
lightning = { git = "https://github.com/lightningdevkit/rust-lightning.git", features = ["max_level_trace"] }
lightning-block-sync = { git = "https://github.com/lightningdevkit/rust-lightning.git", features = [ "rpc-client" ] }
lightning-invoice = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-persister = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-background-processor = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-net-tokio = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
lightning-rapid-gossip-sync = { git = "https://github.com/lightningdevkit/rust-lightning.git" }
log = "0.4.17"
time = "0.3.13"
bitcoin = "0.29.0"
futures = "0.3.28"
io-reactor = "0.1.2"
popol = { version = "2.2.0" }
crossbeam-channel = "0.5.8"

[dev-dependencies]
lampo-nakamoto = { path = "../lampo-nakamoto" }
clightningrpc-conf = { git = "https://github.com/laanwj/cln4rust.git", branch = "master" }
