[package]
name = "lampo-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
lampo-common = { path = "../lampo-common" }
lampod = { path = "../lampod" }
lightning-block-sync = { version = "0.1", features = [ "rpc-client" ] }
log = "0.4.27"
tokio ={ version = "*"}
base64 = "*"
serde = "*"
