[package]
name = "lampo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
lampo-common = { path = "../lampo-common" }
log = { version = "0.4", features = ["std"] }
lexopt = { version = "0.3" }
radicle-term = "0.14.0"
elite-rpc =  { version = "0.0.4", features = ["curl"] }
serde = "*"