[package]
name = "lampod-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
lampod = { path = "../lampod" }
lampo-common = { path = "../lampo-common" }
lampo-nakamoto = { path = "../lampo-nakamoto" }
lampo-jsonrpc = { path = "../lampo-jsonrpc" }
tokio = { version = "1.22.0", features = ["rt"] }
clap = { version = "4.0.26", features = ["derive"] }
log = { version = "0.4", features = ["std"] }
