[package]
name = "lampo-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
lampod = { path = "../lampod" }
lampo-common = { path = "../lampo-common" }
lampo-bitcoind = { path = "../lampo-bitcoind" }
lampo-core-wallet = { path = "../lampo-core-wallet" }
lampo-async-jsonrpc = { path = "../lampo-async-jsonrpc" }
clightning-testing = { git = "https://github.com/laanwj/cln4rust.git" }
log = "0.4.18"
tempfile = "3.6.0"
port-selector = "0.1.6"
anyhow = "1.0.71"
tokio = { version = "1.22.0", features = ["process", "time", "fs"] }
